language: android

android:
  components:
    - extra-google-m2repository
    - extra-android-m2repository
    - platform-tools
    - tools
    - build-tools-27.0.1
    - android-23

before_install:
    - chmod +x gradlew
    - yes | sdkmanager "platforms;android-27"

script:
  ./gradlew build
